import React, { useEffect, useMemo, useRef, useState } from "react";
import { createRoot } from "react-dom/client";
import "./styles.css";

type Template = { id:string; experiment_id:string; adapter:string; adapter_available:boolean; device_id:string; display_name:string; app:{vendor:string;package:string;version:string}; events:Array<{event_type:string}>; defaults:{repetitions_per_event:number;idle_range_seconds:[number,number];cooldown_seconds:number}; network:{target_device_ip?:string|null} };
type Device = { udid:string; state:string; manufacturer?:string; model?:string; android_version?:string; sdk_level?:string; app_version?:string; busy_status:string; last_observation?:{state:string;observed_at_ns:number|null;source:string}|null };
type TaskRequest = { template_id:string; runtime_id:string; mode:"simulate"|"device"|"formal"; udid:string|null; repetitions:number; idle_min_seconds:number; idle_max_seconds:number; cooldown_seconds:number; seed:number|null; target_device_ip:string|null; capture_interface:string|null; capture_filter:string|null; pre_roll_seconds:number|null; post_roll_seconds:number|null };
type Task = { id:string; status:string; stage:string; queue_reason?:string|null; error?:string|null; session_id?:string|null; session_root?:string|null; completed_events:number; planned_events:number; created_at_ns:number; updated_at_ns:number; request:TaskRequest; quality?:{app_success_rate?:number;result_counts?:Record<string,number>}|null };
type Log = { id:number; created_at_ns:number; level:string; stage:string; message:string };
type Session = {session_id:string;updated_at_ns:number;quality:any;validation:any;artifacts:string[];evidence:string[];experiment_id?:string;display_name?:string;device_id?:string;phone_udid?:string;runtime_mode?:string};

const statusName: Record<string,string> = {queued:"排队中",preflight:"预检中",starting:"启动中",running:"运行中",stopping:"停止中",completed:"已完成",failed:"失败",cancelled:"已取消",interrupted:"已中断",idle:"空闲"};
const eventName: Record<string,string> = {turn_on:"开灯",turn_off:"关灯",play_music:"播放音乐",pause_music:"暂停音乐"};
const formalRuntime=(templateId:string)=>templateId==='xiaomi_touchscreen_speaker_music'?'ubuntu-speaker-lab':'ubuntu-lab';
const resultName: Record<string,string> = {confirmed:"独立确认",app_ack_only:"App 已确认，未独立验证",ha_only:"仅独立观测确认",timeout:"超时",unexpected_state:"状态不符合",automation_error:"自动化错误",failed:"失败"};

let controlToken = "";
let defaultRuntimeId = "windows-dev";
async function api<T>(url:string, init:RequestInit={}):Promise<T>{
  const headers = new Headers(init.headers);
  if(init.body) headers.set("content-type","application/json");
  if(init.method && init.method !== "GET") headers.set("x-control-token",controlToken);
  const response = await fetch(url,{...init,headers});
  if(!response.ok) throw new Error((await response.text()) || `请求失败 ${response.status}`);
  return response.json();
}
const fmtTime=(ns:number)=>new Date(ns/1e6).toLocaleString("zh-CN",{hour12:false});
const terminal=(s:string)=>["completed","failed","cancelled","interrupted"].includes(s);

function Badge({value}:{value:string}){return <span className={`badge ${value}`}>{statusName[value]||value}</span>}
function Empty({children}:{children:React.ReactNode}){return <div className="empty">{children}</div>}

function App(){
  const [tab,setTab]=useState("devices");
  const [templates,setTemplates]=useState<Template[]>([]);
  const [devices,setDevices]=useState<Device[]>([]);
  const [deviceError,setDeviceError]=useState("");
  const [tasks,setTasks]=useState<Task[]>([]);
  const [sessions,setSessions]=useState<Session[]>([]);
  const [environment,setEnvironment]=useState<any>(null);
  const [toast,setToast]=useState("");
  const [ready,setReady]=useState(false);
  const [preset,setPreset]=useState<TaskRequest|null>(null);

  const refreshDevices=async()=>{try{const r=await api<{devices:Device[];error:string|null}>("/api/v1/devices");setDevices(r.devices);setDeviceError(r.error||"")}catch(e){setDeviceError(String(e))}};
  const refreshTasks=async()=>{try{setTasks(await api<Task[]>("/api/v1/tasks"))}catch(e){setToast(String(e))}};
  const refreshSessions=async()=>{try{setSessions(await api<Session[]>("/api/v1/sessions"))}catch(e){setToast(String(e))}};
  const refreshEnvironment=async(runtime=defaultRuntimeId)=>{try{setEnvironment(await api(`/api/v1/environment?runtime_id=${runtime}`))}catch(e){setToast(String(e))}};
  useEffect(()=>{(async()=>{const boot=await api<{control_token:string;default_runtime_id:string}>("/api/v1/bootstrap");controlToken=boot.control_token;defaultRuntimeId=boot.default_runtime_id;setTemplates(await api("/api/v1/experiments"));await Promise.all([refreshDevices(),refreshTasks(),refreshSessions(),refreshEnvironment()]);setReady(true)})().catch(e=>setToast(String(e)))},[]);
  useEffect(()=>{if(!ready)return;const taskTimer=setInterval(refreshTasks,1000);const deviceTimer=setInterval(refreshDevices,3000);return()=>{clearInterval(taskTimer);clearInterval(deviceTimer)}},[ready]);
  useEffect(()=>{if(toast){const id=setTimeout(()=>setToast(""),5000);return()=>clearTimeout(id)}},[toast]);
  const running=tasks.filter(t=>!terminal(t.status)).length;
  const nav=[['devices','设备与环境'],['create','创建实验'],['runs',`运行中心${running?` · ${running}`:''}`],['history','历史与结果'],['settings','环境设置']];
  return <div className="shell">
    <aside><div className="brand"><div className="mark">HA</div><div><strong>实验控制台</strong><small>IoT Automation</small></div></div><nav>{nav.map(([id,label])=><button key={id} className={tab===id?'active':''} onClick={()=>setTab(id)}>{label}</button>)}</nav><div className="aside-foot"><span className="pulse"/>仅限本机访问</div></aside>
    <main><header><div><h1>{nav.find(n=>n[0]===tab)?.[1]}</h1><p>从设备检查到实验证据，全程保留可追溯记录</p></div><div className="header-stat"><b>{devices.filter(d=>d.state==='device').length}</b><span>台手机在线</span></div></header>
      {tab==='devices'&&<Devices devices={devices} error={deviceError} templates={templates} onRefresh={refreshDevices}/>}
      {tab==='create'&&<Create templates={templates} devices={devices} preset={preset} onCreated={()=>{refreshTasks();setTab('runs')}} notify={setToast}/>}
      {tab==='runs'&&<Runs tasks={tasks} notify={setToast}/>}
      {tab==='history'&&<History sessions={sessions} tasks={tasks} onRefresh={refreshSessions} onReuse={value=>{setPreset(value);setTab('create');setToast('已回填历史任务参数，请检查后再启动')}}/>}
      {tab==='settings'&&<Settings data={environment} onRefresh={refreshEnvironment}/>}
    </main>{toast&&<div className="toast">{toast}</div>}
  </div>
}

function Devices({devices,error,templates,onRefresh}:{devices:Device[];error:string;templates:Template[];onRefresh:()=>void}){
 return <section><div className="toolbar"><div><h2>Android 手机</h2><p>连接状态来自 ADB；IoT 设备在线状态需独立观测后才能确认。</p></div><button className="secondary" onClick={onRefresh}>刷新设备</button></div>{error&&<div className="alert error">{error}</div>}
  <div className="cards">{devices.length?devices.map(d=><article className="device-card" key={d.udid}><div className="card-top"><div className="phone-icon">▯</div><Badge value={d.state==='device'?'running':d.state}/></div><h3>{d.manufacturer||'Android'} {d.model||'未知型号'}</h3><code>{d.udid}</code><dl><div><dt>Android</dt><dd>{d.android_version||'—'} / SDK {d.sdk_level||'—'}</dd></div><div><dt>目标 App</dt><dd>{d.app_version||'未检测到'}</dd></div><div><dt>任务占用</dt><dd>{statusName[d.busy_status]||d.busy_status}</dd></div><div><dt>IoT 状态</dt><dd>{d.last_observation?`${d.last_observation.state} · ${d.last_observation.observed_at_ns?fmtTime(d.last_observation.observed_at_ns):'时间未知'} · App`:'连接状态未验证'}</dd></div></dl></article>):<Empty>未发现设备。请连接手机并确认 USB 调试授权。</Empty>}</div>
  <div className="section-gap"><h2>已接入实验设备</h2><div className="table"><div className="tr head"><span>设备</span><span>设备 ID</span><span>厂商 App</span><span>独立状态</span></div>{templates.map(t=><div className="tr" key={t.id}><span><b>{t.display_name}</b></span><span><code>{t.device_id}</code></span><span>{t.app.vendor} · {t.app.version}</span><span className="muted">未配置</span></div>)}</div></div>
 </section>
}

const blank=(t?:Template):TaskRequest=>({template_id:t?.id||'',runtime_id:defaultRuntimeId,mode:'simulate',udid:null,repetitions:t?.defaults.repetitions_per_event||1,idle_min_seconds:t?.defaults.idle_range_seconds[0]||1,idle_max_seconds:t?.defaults.idle_range_seconds[1]||3,cooldown_seconds:t?.defaults.cooldown_seconds||1,seed:null,target_device_ip:t?.network.target_device_ip||null,capture_interface:null,capture_filter:null,pre_roll_seconds:null,post_roll_seconds:null});
function Create({templates,devices,preset,onCreated,notify}:{templates:Template[];devices:Device[];preset:TaskRequest|null;onCreated:()=>void;notify:(s:string)=>void}){
 const [form,setForm]=useState<TaskRequest>(()=>blank(templates[0]));const [queue,setQueue]=useState<TaskRequest[]>([]);const [advanced,setAdvanced]=useState(false);const [checking,setChecking]=useState(false);const first=templates[0];
 useEffect(()=>{if(!form.template_id&&first)setForm(blank(first))},[first]);
 useEffect(()=>{if(preset)setForm({...preset})},[preset]);
 const patch=(v:Partial<TaskRequest>)=>setForm(f=>({...f,...v}));
 const changeTemplate=(id:string)=>{const t=templates.find(x=>x.id===id);setForm(f=>({...blank(t),mode:f.mode,udid:f.udid,runtime_id:f.mode==='formal'?formalRuntime(id):f.runtime_id}))};
 const validate=(item=form)=>{if(!item.template_id)throw new Error('请选择实验项目');if(item.mode!=='simulate'&&!item.udid)throw new Error('请选择手机在线设备');if(item.mode==='formal'&&(!item.capture_interface||!item.capture_filter||!item.target_device_ip))throw new Error('正式采集必须填写目标设备 IP、抓包接口和过滤器')};
 const preflight=async()=>{try{validate();setChecking(true);const r:any=await api('/api/v1/preflights',{method:'POST',body:JSON.stringify(form)});notify(r.ok?'预检通过':'预检存在失败项，请检查环境设置')}catch(e){notify(String(e))}finally{setChecking(false)}};
 const add=()=>{try{validate();setQueue(q=>[...q,form]);notify('已加入待提交列表')}catch(e){notify(String(e))}};
 const submit=async()=>{const all=queue.length?queue:[form];try{all.forEach(validate);await api('/api/v1/tasks',{method:'POST',body:JSON.stringify({client_request_id:crypto.randomUUID(),tasks:all})});setQueue([]);onCreated()}catch(e){notify(String(e))}};
 return <section className="two-col"><div className="panel"><h2>实验参数</h2><div className="form-grid"><label>实验项目<select value={form.template_id} onChange={e=>changeTemplate(e.target.value)}>{templates.map(t=><option key={t.id} value={t.id}>{t.display_name}</option>)}</select></label><label>运行方式<select value={form.mode} onChange={e=>patch({mode:e.target.value as any,runtime_id:e.target.value==='formal'?formalRuntime(form.template_id):defaultRuntimeId})}><option value="simulate">模拟运行</option><option value="device">真机验证</option><option value="formal">正式采集</option></select></label>{form.mode!=='simulate'&&<label className="wide">运行手机<select value={form.udid||''} onChange={e=>patch({udid:e.target.value})}><option value="">请选择在线手机</option>{devices.filter(d=>d.state==='device').map(d=><option key={d.udid} value={d.udid}>{d.manufacturer} {d.model} · {d.udid}</option>)}</select></label>}<label>每种事件次数<input type="number" min="1" value={form.repetitions} onChange={e=>patch({repetitions:+e.target.value})}/></label><label>冷却时间（秒）<input type="number" min="0" step="0.1" value={form.cooldown_seconds} onChange={e=>patch({cooldown_seconds:+e.target.value})}/></label><label>最短等待（秒）<input type="number" min="0" step="0.1" value={form.idle_min_seconds} onChange={e=>patch({idle_min_seconds:+e.target.value})}/></label><label>最长等待（秒）<input type="number" min="0" step="0.1" value={form.idle_max_seconds} onChange={e=>patch({idle_max_seconds:+e.target.value})}/></label></div><button className="link" onClick={()=>setAdvanced(!advanced)}>{advanced?'收起':'展开'}高级参数</button>{advanced&&<div className="form-grid advanced"><label>随机种子<input type="number" placeholder="自动生成" value={form.seed||''} onChange={e=>patch({seed:e.target.value?+e.target.value:null})}/></label><label>目标设备 IP<input placeholder="可选" value={form.target_device_ip||''} onChange={e=>patch({target_device_ip:e.target.value||null})}/></label><label className="wide">抓包接口<input placeholder="正式采集必填" value={form.capture_interface||''} onChange={e=>patch({capture_interface:e.target.value||null})}/></label><label className="wide">抓包过滤器<input placeholder="例如 host 192.168.1.20" value={form.capture_filter||''} onChange={e=>patch({capture_filter:e.target.value||null})}/></label></div>}<div className="actions"><button className="secondary" disabled={checking} onClick={preflight}>{checking?'检查中…':'先做预检'}</button><button className="secondary" onClick={add}>加入批次</button><button className="primary" onClick={submit}>启动{queue.length?` ${queue.length} 个`:''}实验</button></div></div>
 <div className="panel summary"><h2>本次运行</h2><div className="experiment-name">{templates.find(t=>t.id===form.template_id)?.display_name||'—'}</div><p>{form.mode==='simulate'?'模拟运行不会连接真机或启动抓包。':form.mode==='formal'?'正式采集将在预检通过后控制设备并启动连续抓包。':'真机验证将控制所选手机，不启动抓包。'}</p><dl><div><dt>计划事件</dt><dd>{form.repetitions*(templates.find(t=>t.id===form.template_id)?.events.length||0)}</dd></div><div><dt>事件类型</dt><dd>{templates.find(t=>t.id===form.template_id)?.events.map(e=>eventName[e.event_type]||e.event_type).join('、')||'—'}</dd></div><div><dt>设备</dt><dd>{form.mode==='simulate'?'模拟设备':form.udid||'未选择'}</dd></div><div><dt>IoT 在线状态</dt><dd>未独立验证</dd></div></dl>{queue.length>0&&<><h3>待提交批次</h3>{queue.map((q,i)=><div className="queue-item" key={i}><span>{templates.find(t=>t.id===q.template_id)?.display_name}</span><button onClick={()=>setQueue(v=>v.filter((_,n)=>n!==i))}>移除</button></div>)}</>}</div></section>
}

function Runs({tasks,notify}:{tasks:Task[];notify:(s:string)=>void}){
 const [selected,setSelected]=useState<string>('');const [logs,setLogs]=useState<Log[]>([]);const [paused,setPaused]=useState(false);const [level,setLevel]=useState('all');const [query,setQuery]=useState('');const cursor=useRef(0);const task=tasks.find(t=>t.id===selected)||tasks[0];
 useEffect(()=>{if(task&&task.id!==selected)setSelected(task.id)},[task?.id]);
 useEffect(()=>{cursor.current=0;setLogs([])},[selected]);
 useEffect(()=>{if(!selected||paused)return;const load=async()=>{try{const rows=await api<Log[]>(`/api/v1/tasks/${selected}/logs?after=${cursor.current}`);if(rows.length){cursor.current=rows.at(-1)!.id;setLogs(v=>[...v,...rows].slice(-1000))}}catch{}};load();const id=setInterval(load,1000);return()=>clearInterval(id)},[selected,paused]);
 const mutate=async(action:string)=>{try{await api(`/api/v1/tasks/${task.id}/${action}`,{method:'POST'});notify(action==='stop'?'已请求安全停止':'已强制终止任务')}catch(e){notify(String(e))}};
 const shown=logs.filter(l=>(level==='all'||l.level===level)&&(!query||`${l.stage} ${l.message}`.toLowerCase().includes(query.toLowerCase())));
 const forceReady=task?.status==='stopping'&&(Date.now()-task.updated_at_ns/1e6)>=60000;
 return <section className="runs-layout"><div className="task-list"><h2>实验任务</h2>{tasks.length?tasks.map(t=><button key={t.id} className={t.id===task?.id?'selected':''} onClick={()=>setSelected(t.id)}><div><b>{t.request.template_id}</b><small>{t.session_id||t.id.slice(0,10)}</small></div><Badge value={t.status}/><progress max={Math.max(t.planned_events,1)} value={t.completed_events}/></button>):<Empty>还没有实验任务。</Empty>}</div>{task?<div className="run-detail"><div className="run-head"><div><Badge value={task.status}/><h2>{task.request.template_id}</h2><p>{task.session_id||'会话将在启动后生成'}</p></div>{!terminal(task.status)&&<div className="actions"><button className="danger-soft" onClick={()=>mutate('stop')}>安全停止</button>{forceReady&&<button className="danger" onClick={()=>mutate('force-stop')}>强制终止</button>}</div>}</div>{task.queue_reason&&<div className="alert">{task.queue_reason}</div>}{task.status==='stopping'&&!forceReady&&<div className="alert">正在清理资源；安全停止超过 60 秒后才会提供强制终止。</div>}{task.error&&<div className="alert error">{task.error}</div>}<div className="metrics"><div><strong>{task.completed_events} / {task.planned_events}</strong><span>已完成事件</span></div><div><strong>{task.quality?.app_success_rate!=null?`${(task.quality.app_success_rate*100).toFixed(1)}%`:'—'}</strong><span>App 回执成功率</span></div><div><strong>{task.request.mode==='simulate'?'模拟':task.request.mode==='formal'?'正式':'真机'}</strong><span>运行类型</span></div></div>{task.quality?.result_counts&&<div className="results">{Object.entries(task.quality.result_counts).map(([k,v])=><span key={k}>{resultName[k]||k} <b>{v}</b></span>)}</div>}<div className="log-head"><h3>运行日志</h3><div className="actions"><input className="log-search" placeholder="筛选日志" value={query} onChange={e=>setQuery(e.target.value)}/><select value={level} onChange={e=>setLevel(e.target.value)}><option value="all">全部级别</option><option value="info">信息</option><option value="warning">警告</option><option value="error">错误</option></select><button className="secondary small" onClick={()=>setPaused(!paused)}>{paused?'继续滚动':'暂停滚动'}</button><button className="secondary small" onClick={()=>{const blob=new Blob([logs.map(l=>`${fmtTime(l.created_at_ns)} [${l.stage}] ${l.message}`).join('\n')],{type:'text/plain'});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=`${task.id}.log`;a.click();URL.revokeObjectURL(a.href)}}>下载</button></div></div><div className="console">{shown.length?shown.map(l=><div key={l.id} className={l.level}><time>{fmtTime(l.created_at_ns)}</time><span>{l.stage}</span><p>{l.message}</p></div>):<p className="muted">没有匹配的日志。</p>}</div></div>:<Empty>选择一个任务查看运行详情。</Empty>}</section>
}

function History({sessions,tasks,onRefresh,onReuse}:{sessions:Session[];tasks:Task[];onRefresh:()=>void;onReuse:(r:TaskRequest)=>void}){const [query,setQuery]=useState('');const [quality,setQuality]=useState('all');const filtered=sessions.filter(s=>(!query||`${s.session_id} ${s.display_name||''} ${s.phone_udid||''}`.toLowerCase().includes(query.toLowerCase()))&&(quality==='all'||(quality==='ok'?s.validation?.ok:!s.validation?.ok)));return <section><div className="toolbar"><div><h2>实验会话</h2><p>失败和中断会话同样保留，便于追溯原始证据。</p></div><div className="actions"><input placeholder="搜索会话、设备或手机" value={query} onChange={e=>setQuery(e.target.value)}/><select value={quality} onChange={e=>setQuality(e.target.value)}><option value="all">全部结果</option><option value="ok">校验通过</option><option value="bad">失败或不完整</option></select><button className="secondary" onClick={onRefresh}>刷新历史</button></div></div><div className="table sessions"><div className="tr head"><span>会话 / 实验</span><span>更新时间</span><span>质量</span><span>校验</span><span>产物与操作</span></div>{filtered.length?filtered.map(s=>{const source=tasks.find(t=>t.session_id===s.session_id);return <div className="tr" key={s.session_id}><span><b>{s.session_id}</b><small>{s.display_name||s.experiment_id||''}{s.phone_udid?` · ${s.phone_udid}`:''}</small></span><span>{fmtTime(s.updated_at_ns)}</span><span>{s.quality?`${((s.quality.app_success_rate||0)*100).toFixed(1)}%`:'未生成'}</span><span>{s.validation?.ok?'通过':'不完整'}</span><span className="artifact-links">{s.artifacts.filter(a=>['quality_report.json','actions.jsonl','run_journal.jsonl','appium.log','traffic.pcapng','ha_reconciliation.json','pcap_review.json','ha_history.json','ha_clock_probe.json'].includes(a)).map(a=><a key={a} href={`/api/v1/sessions/${s.session_id}/artifacts/${a}`}>{a}</a>)}{s.evidence.map(a=><a key={a} href={`/api/v1/sessions/${s.session_id}/evidence/${a}`}>证据：{a}</a>)}{source&&<button className="link" onClick={()=>onReuse(source.request)}>使用该参数新建</button>}</span></div>}):<Empty>没有匹配的实验会话。</Empty>}</div></section>}

function Settings({data,onRefresh}:{data:any;onRefresh:(r?:string)=>void}){const [runtime,setRuntime]=useState(defaultRuntimeId);return <section><div className="toolbar"><div><h2>运行环境</h2><p>正式采集的必要检查失败时，平台会阻止真实动作。</p></div><div className="actions"><select value={runtime} onChange={e=>{setRuntime(e.target.value);onRefresh(e.target.value)}}><option value="windows-dev">Windows 开发</option><option value="ubuntu-dev">Ubuntu 开发</option><option value="ubuntu-lab">Ubuntu 正式</option><option value="ubuntu-speaker-lab">Ubuntu 音箱正式</option></select><button className="secondary" onClick={()=>onRefresh(runtime)}>重新检查</button></div></div>{data?<><div className="check-grid">{data.checks.map((c:any)=><article className={c.ok?'ok':'fail'} key={c.name}><span>{c.ok?'✓':'!'}</span><div><b>{c.name}</b><small>{typeof c.detail==='string'?c.detail:JSON.stringify(c.detail)}</small></div></article>)}</div><div className="panel section-gap"><h2>抓包接口</h2>{data.capture_interfaces.length?<ul className="interfaces">{data.capture_interfaces.map((x:string)=><li key={x}>{x}</li>)}</ul>:<p className="muted">没有检测到可用接口，开发模式可继续使用。</p>}</div></>:<Empty>正在检查运行环境…</Empty>}</section>}

createRoot(document.getElementById("root")!).render(<React.StrictMode><App/></React.StrictMode>);
